- name: Package with loop
  block:
  - name: Failloop
    shell: "rpm -qa | grep {{ item }}"
    become: true
    loop:
      - failme

  always:

    - name: debug
      debug:
        msg: "Done!"

