---
- hosts: localhost
  gather_facts: no
  environment:
#    http_proxy: 'ec2-18-216-94-161.us-east-2.compute.amazonaws.com:3128'
#    https_proxy: 'ec2-18-216-94-161.us-east-2.compute.amazonaws.com:3128'
  tasks:
  - name: "Change ec2 instances to state: {{state}}"
    ec2:
      state: "stopped"
      instance_tags:
          Name: "dluong-ah"   
      region: "us-east-2"
      wait: yes
    delegate_to: dluong-at
    register: instances

