---
- hosts: localhost
  gather_facts: no
  environment:
#    http_proxy: '18.216.94.161:3128'
#    https_proxy: '18.216.94.161:3128'
  tasks:
  - name: "Change ec2 instances to state: {{state}}"
    ec2:
      state: "stopped"
      instance_tags:
          Name: "dluong-delete"   
      region: "us-east-2"
      wait: yes
    delegate_to: dluong-ah
    register: instances

