---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: "Change ec2 instances to state: {{state}}"
    ec2:
      state: "stopped"
      instance_tags:
          Name: "dluong-ah"   
      region: "us-east-2"
      wait: yes
    register: instances

