- name: local info
  hosts: all
  gather_facts: no

  tasks:
    - name: ls -l
      become_user: awx
      local_action:
        module: shell ls -l 

    - name: pwd
      become_user: awx
      local_action:
        module: pwd

