---
- name: Test Script
  hosts: all
  gather_facts: no
  vars:
    - ansible_connection: winrm
    - ansible_winrm_transport: ntlm
    - ansible_winrm_server_cert_validation: ignore
    - logpath: test\
  tasks:
    - name: Copy script
      win_copy:
        src: "./testps.ps1"
        dest: 'c:\users\public\'
        remote_src: no

    - name: Run Script Block
      block:
        - name: Run Script
#          script: c:\users\public\testps.ps1 -csv "{{ csv }}" -logpath "{{ logpath }}"
          script: testps.ps1 -csv "testing" -logpath "logpath"
      always:
        - name: Remove Script
          win_file:
            path: 'c:\users\public\testps.ps1'
            state: absent
