---
- hosts: localhost
  tasks:
  - name: Export all assets
    ansible.tower.tower_export:
      all: True
    register: export_output

  - name: Import all tower assets from our export
    ansible.tower.tower_import:
      assets: "{{ export_output.assets }}"
