---
- hosts: localhost
  tasks:
  - name: Export all assets
    awx.awx.tower_export:
      all: True
    register: export_output

  - name: Import all tower assets from our export
    awx.awx.tower_import:
      assets: "{{ export_output }}"
