---
- hosts: all
  vars:
    - ansible_connection: winrm
    - ansible_winrm_transport: ntlm
    - ansible_winrm_server_cert_validation: ignore
  tasks:
  - set_fact: test="!unsafe {{ survey }}"
  - win_command: echo "{{ test }}"
    
