---
- hosts: all
  vars:
    - ansible_connection: winrm
    - ansible_winrm_transport: ntlm
    - ansible_winrm_server_cert_validation: ignore
    - test: !unsafe "{{ survey }}"
  tasks:
  - win_command: echo "{{ test }}"
    
