---
- hosts: all
  vars:
    - ansible_connection: winrm
    - ansible_winrm_transport: ntlm
    - ansible_winrm_server_cert_validation: ignore
    - test: "{{ survey }}"
  tasks:
  - win_command: powershell.exe echo "{{ test }}"
    
